version: '3.1'

networks:
  insta_network:
    driver: bridge

services:
  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: insta
    networks:
      - insta_network
    ports:
      - "3306:3306"
    volumes:
      - "./sql/dump.sql:/docker-entrypoint-initdb.d/dump.sql"


  backend:
    build:
      context: ./dockers
      dockerfile: DockerFilePHP
    networks:
      - insta_network
    ports:
      - "80:80"
    command: apachectl -D FOREGROUND
    volumes:
      - './api:/var/www/html'
      - './000-default.conf:/etc/apache2/sites-available/000-default.conf'
      - './apache2.conf:/etc/apache2/apache2.conf'

  frontend:
    build:
      context: ./dockers
      dockerfile: DockerFileVue
    networks:
      - insta_network
    ports:
      - "8080:8080"
    command: >
      bash -c "cd /home/insta/frontend && npm install && npm run dev"
    volumes:
      - './frontend/insta:/home/insta/frontend'
    env_file:
      - './settings.ini'